ASKEducationAdmin/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ask.Controllers
{
    public class SpecController : Controller
    {
        //
        // GET: /City/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ASKEducationAdmin/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;

namespace ask.Controllers
{
    public class CourseController : Controller
    {
        //
        // GET: /Course/
        


        public ActionResult Index()
        {
            MySqlConnection Connection = new MySqlConnection("Database=u0066974_ask_education;Data Source=37.140.192.132;User Id=u0066_root;Password=gEt7m29&");
            
            string sSQL = @"SELECT * FROM countries";

            DataTable dt = new DataTable();

            using (Connection)
            {
                Connection.Open();

                MySqlCommand com = new MySqlCommand(sSQL, Connection);
            
                using (MySqlDataReader dr = com.ExecuteReader())
                {
                    //есть записи?
                    if (dr.HasRows)
                    {
                        try
                        {

                            dt.Load(dr);
                        }
                        catch (Exception e)
                        {
                        }
                    }
                }
            }

            Connection.Close();
            
            ViewBag.countries = dt;

            return View();
        }

        /*[HttpPost]
        public ActionResult DropSchoolBind(string courseId, string schoolId)
        {
            var connection = new MySqlConnection("Database=u0066974_ask_education;Data Source=37.140.192.132;User Id=u0066_root;Password=gEt7m29&");

            //var sql = @"DELETE FROM links WHERE links.courseId = " + courseId + " AND links.schoolId = " + schoolId;
            var sql = @"SELECT * FROM countries";

            using (connection)
            {
                connection.Open();

                var com = new MySqlCommand(sql, connection);

                return Json(com, JsonRequestBehavior.AllowGet);
            }

        }*/


    }
}

ASKEducationAdmin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ask.Controllers
{
    public class LoginController : Controller
    {
        private const string User = "admin";
        private const string Pass = "admin";
        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Login(String username, String password)
        {

            if (username == User && password == Pass)
            {
                FormsAuthentication.SetAuthCookie(username, true);
                return RedirectToAction("Index", "Home");
            }
            return Json("ok");
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

    }
}

ASKEducationAdmin/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;

namespace ask.Controllers
{
    public class ReviewController : Controller
    {
        //
        // GET: /Review/

        public ActionResult Index()
        {

            MySqlConnection Connection = new MySqlConnection("Database=u0066974_ask_education;Data Source=127.0.0.1;User Id=u0066_root;Password=gEt7m29&");



            string sSQL = @"SELECT * FROM countries";

            string city = @"SELECT * FROM city";

            DataTable dt = new DataTable();

            DataTable ct = new DataTable();

            using (Connection)
            {
                Connection.Open();

                MySqlCommand com = new MySqlCommand(sSQL, Connection);

                using (MySqlDataReader dr = com.ExecuteReader())
                {
                    //есть записи?
                    if (dr.HasRows)
                    {
                        try
                        {

                            dt.Load(dr);
                        }
                        catch (Exception e)
                        {
                        }
                    }
                }


            }

            using (Connection)
            {
                Connection.Open();

                MySqlCommand com = new MySqlCommand(city, Connection);

                using (MySqlDataReader ds = com.ExecuteReader())
                {
                    //есть записи?
                    if (ds.HasRows)
                    {
                        //заполняем объект DataTable
                        ct.Load(ds);
                    }
                }


            }



            ViewBag.countries = dt;
            ViewBag.city = ct;

            return View();
        }

    }
}

ASKEducationAdmin/Views/Shared/PartialCountries.cshtml
<option value="Австралия">Австралия</option>
<option value="Великобритания">Великобритания</option>
<option value="Германия">Германия</option>
<option value="Голландия">Голландия</option>
<option value="Ирландия">Ирландия</option>
<option value="Испания">Испания</option>
<option value="Италия">Италия</option>
<option value="Канада">Канада</option>
<option value="Кипр">Кипр</option>
<option value="Китай">Китай</option>
<option value="Коста-Рика">Коста-Рика</option>
<option value="Малайзия">Малайзия</option>
<option value="Мальта">Мальта</option>
<option value="Россия">Россия</option>
<option value="Сингапур">Сингапур</option>
<option value="США">США</option>
<option value="Франция">Франция</option>
<option value="Чехия">Чехия</option>
<option value="Швейцария">Швейцария</option>
<option value="ЮАР">ЮАР</option>
<option value="Южная Корея">Южная Корея</option>
<option value="Япония">Япония</option>

ASKEducationAdmin/Views/Shared/PartialCurrencyTypes.cshtml
<option value="643">РУБ</option>
<option value="840">USD</option>
<option value="978">EUR</option>
<option value="826">GBP</option>
<option value="124">CAD</option>
<option value="036">AUD</option>
<option value="756">CHF</option>
<option value="554">NZD</option>
<option value="156">CNY</option>

ASKEducationAdmin/Views/Shared/PartialLangs.cshtml
<option value="Английский">Английский</option>
<option value="Испанский">Испанский</option>
<option value="Итальянский">Итальянский</option>
<option value="Китайский">Китайский</option>
<option value="Корейский">Корейский</option>
<option value="Немецкий">Немецкий</option>
<option value="Французский">Французский</option>
<option value="Японский">Японский</option>
<option value="Чешский">Чешский</option>
<option value="Греческий">Греческий</option>

ASKEducationAdmin/Views/Shared/PartialMenu.cshtml
<li class="start active open">
    <a href="javascript:;">
        <i class="icon-home"></i>
        <span class="title">Контент</span>
        <span class="selected"></span>
        <span class="arrow open"></span>
    </a>
    <ul class="sub-menu">
        <li class="open">
            <a href="javascript:;">
                <i class="icon-login"></i>
                <span class="title">Школы</span>
                <span class="arrow open"></span>
            </a>
            <ul class="sub-menu" style="display: block;">
                <li>
                    <a href="@Url.Action("index", "School")">
                        <i class="icon-pencil"></i>
                        Редактировать
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("index", "Spec")">
                        <i class="icon-pencil"></i>
                        Специализации
                    </a>
                </li>
            </ul>
        </li>
        <li class="open">
            <a href="javascript:;">
                <i class="icon-logout"></i>
                <span class="title">Курсы</span>
                <span class="arrow open"></span>
            </a>
            <ul class="sub-menu" style="display: block;">
                <li>
                    <a href="@Url.Action("index", "Course")">
                        <i class="icon-pencil"></i>
                        Редактировать
                    </a>
                </li>
            </ul>
        </li>
        <!--<li class="open">
            <a href="javascript:;">
                <i class="icon-login"></i>
                <span class="title">Стажировка</span>
                <span class="arrow open"></span>
            </a>
            <ul class="sub-menu" style="display: block;">
                <li>
                    <a href="@Url.Action("index", "group")">
                        <i class="icon-users"></i>
                        Собрать свою группу
                    </a>
                </li>
            </ul>
        </li>-->
        <li>
            <a href="@Url.Action("Index", "blog")">
                <i class="icon-calculator"></i>
                <span class="title">Блог</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "about")">
                <i class="icon-bar-chart"></i>
                <span class="title">О нас</span>
            </a>
        </li>
        <!--<li class="open">
            <a href="@Url.Action("Index", "help")">
                <i class="icon-bar-chart"></i>
                <span class="title">Помощь</span>
            </a>
        </li>
        <li class="open">
            <a href="@Url.Action("Index", "agency")">
                <i class="icon-bar-chart"></i>
                <span class="title">Агентствам</span>
            </a>
        </li>-->
        <li>
            <a href="@Url.Action("Index", "countries")">
                <i class="icon-bar-chart"></i>
                <span class="title">Страны</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Review")">
                <i class="icon-speech"></i>
                <span class="title">Отзывы</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "city")">
                <i class="icon-home"></i>
                <span class="title">Города</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "pages")">
                <i class="icon-home"></i>
                <span class="title">Описание разделов</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Subscribe")">
                <i class="icon-home"></i>
                <span class="title">Подписки</span>
            </a>
        </li>
        <!--
        <li class="open">
            <a href="javascript:;">
                <i class="icon-logout"></i>
                <span class="title">Учителям</span>
                <span class="arrow open"></span>
            </a>
            <ul class="sub-menu" style="display: block;">
                <li>
                    <a href="@Url.Action("index", "Сooperation")">
                        <i class="icon-list"></i>
                        Сотрудничество
                    </a>
                </li>
            </ul>
        </li>-->
    </ul>
</li>

ASKEducationAdmin/Views/Shared/PartialschoolTypes.cshtml
<option value="individual">Языковые школы</option>
<option value="higher">Высшее образование</option>
<option value="secondary">Среднее образование</option>

ASKEducationAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="ru" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <title>@ViewBag.Title</title>

    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
    <link href="~/Content/css/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/css/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/css/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    @*<link href="~/Content/css/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>*@
    @*<link href="~/Content/css/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>*@

    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
    @*<link href="~/Content/css/bootstrap-daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/css/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/css/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css"/>*@
    <!-- END PAGE LEVEL PLUGIN STYLES -->
    <!-- BEGIN PAGE STYLES -->
    @*<link href="~/Content/css/tasks.css" rel="stylesheet" type="text/css"/>*@
    <!-- END PAGE STYLES -->
    <!-- BEGIN THEME STYLES -->
    <!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
    <link href="~/Content/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
    <link href="~/Content/css/plugins.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/css/layout.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/css/themes/darkblue.css" rel="stylesheet" type="text/css" id="style_color"/>

    <link href="~/Content/css/custom.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="~/Content/images/favicon.ico"/>
    <!-- END HEAD -->
    <!-- BEGIN BODY -->
    <!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
    <!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
    <!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
    <!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
    <!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
    <!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
    <!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->
    @Styles.Render("~/Content/css")
</head>
<body class="page-header-fixed page-quick-sidebar-over-content page-style-square page-sidebar-fixed"> 
 <!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
	<div class="page-header-inner">
		<!-- BEGIN LOGO -->
		<div class="page-logo">
			<a href="/">
			<img src="~/Content/images/logo.png" alt="logo" class="logo-default"/>
			</a>
			<div class="menu-toggler sidebar-toggler hide">
				<!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
			</div>
		</div>
		<!-- END LOGO -->
		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
		</a>
		<!-- END RESPONSIVE MENU TOGGLER -->
	    <!-- BEGIN TOP NAVIGATION MENU -->
        
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <!-- BEGIN USER LOGIN DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    <li class="dropdown dropdown-user">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <img alt="" class="img-circle" src="~/Content/images/avatar3_small.jpg" />
                            <span class="username username-hide-on-mobile">
                                @Html.Encode(User.Identity.Name)
                            </span>
                            <i class="fa fa-angle-down"></i>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="#">
                                    <i class="icon-user"></i> Учетная запись
                                </a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="@Url.Action("Logout", "Login")">
                                    <i class="icon-key"></i> Выйти
                                </a>

                            </li>
                        </ul>

                    </li>
                    <!-- END USER LOGIN DROPDOWN -->
                </ul>
            </div>
		<!-- END TOP NAVIGATION MENU -->
	</div>
	<!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
<div class="clearfix"></div>
<!-- BEGIN CONTAINER -->
<div class="page-container">
	<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar-wrapper">
		<div class="page-sidebar navbar-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->
			<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
			<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
			<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
			<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
			<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
			<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
			<ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
				<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
				<li class="sidebar-toggler-wrapper">
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
					<div class="sidebar-toggler">
					</div>
					<!-- END SIDEBAR TOGGLER BUTTON -->
				</li>
				<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
				<li class="sidebar-search-wrapper">
					<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
					<!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
					<!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
					<form class="sidebar-search " action="extra_search.html" method="POST">
						<a href="javascript:;" class="remove">
						<i class="icon-close"></i>
						</a>
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Поиск...">
							<span class="input-group-btn">
							<a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
							</span>
						</div>
					</form>
					<!-- END RESPONSIVE QUICK SEARCH FORM -->
				</li>
                @Html.Partial("PartialMenu")
			   
            </ul>
			<!-- END SIDEBAR MENU -->
		</div>
	</div>
	<!-- END SIDEBAR -->
	<!-- BEGIN CONTENT -->
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">Настройки виджета</h4>
						</div>
						<div class="modal-body">
							 ...
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">Сохранить</button>
							<button type="button" class="btn default" data-dismiss="modal">Закрыть</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">@ViewBag.Title</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/">Главная</a>
						<i class="fa fa-angle-right"></i>
                        <span>@{@ViewBag.Title}</span>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<div class="clearfix">
			</div>
             @RenderBody()
			<div class="clearfix">
			</div>
		</div>
	</div>
	<!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
   


    <!-- BEGIN FOOTER -->
    <div class="page-footer">
	    <div class="page-footer-inner">
		     2015 &copy; ASK Education
	    </div>
	    <div class="scroll-to-top">
		    <i class="icon-arrow-up"></i>
	    </div>
    </div>
    <!-- END FOOTER -->

    <div class="s-grid"></div>

    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->
    <script src="~/Content/js/jquery.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery-migrate.min.js" type="text/javascript"></script>
    <!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src="~/Content/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.cokie.min.js" type="text/javascript"></script>
    @*<script src="~/Content/js/jquery.uniform.min.js" type="text/javascript"></script>*@
    @*<script src="~/Content/js/bootstrap-switch.min.js" type="text/javascript"></script>*@
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
@*    <script src="~/Content/js/jquery.flot.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.flot.resize.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.flot.categories.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.pulsate.min.js" type="text/javascript"></script>
    <script src="~/Content/js/moment.min.js" type="text/javascript"></script>
    <script src="~/Content/js/daterangepicker.js" type="text/javascript"></script>*@
    <!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
@*    <script src="~/Content/js/fullcalendar.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.easypiechart.min.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery.sparkline.min.js" type="text/javascript"></script>*@
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="~/Content/js/metronic.js" type="text/javascript"></script>
    <script src="~/Content/js/layout.js" type="text/javascript"></script>
    @*<script src="~/Content/js/quick-sidebar.js" type="text/javascript"></script>*@
    <script src="~/Content/js/demo.js" type="text/javascript"></script>
    <script src="~/Content/js/index.js" type="text/javascript"></script>
    <script src="~/Content/js/tasks.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script src="~/Content/js/sovetnikAplication.js" type="text/javascript"></script>
    <script>
        jQuery(document).ready(function () {
            Metronic.init(); // init metronic core componets
            Layout.init(); // init layout
            //QuickSidebar.init(); // init quick sidebar
            Demo.init(); // init demo features 
            Index.init();
            //Index.initDashboardDaterange();
            //Index.initJQVMAP(); // init index page's custom scripts
            //Index.initCalendar(); // init index page's custom scripts
            //Index.initCharts(); // init index page's custom scripts
            //Index.initChat();
            //Index.initMiniCharts();
            //Tasks.initDashboardWidget();
        });
    </script>
        @RenderSection("scripts", required: false)
    <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>